name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/opensuse/tumbleweed:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          zypper addrepo --refresh --enable https://download.opensuse.org/repositories/Base:System/openSUSE_Tumbleweed/Base:System.repo
          zypper --non-interactive --gpg-auto-import-keys install --no-recommends make clang gcc bpftool libbpf1 libbpf-devel diffutils scx-devel
      - name: Build
        run:  make all


